<?php
/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-8-15
 * Time: 上午10:59
 */
class Controller_Admin extends Admin
{
    private $admin;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->admin =  new Model_Admin();
    }

    public function listAction()
    {
        $data = $this->_request->getPost();
        $list = $this->admin->getList($data);
        $this->assign('list',$list);
        $this->display();
    }

}