<?php
/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-8-14
 * Time: 下午5:35
 */
class Controller_Customer extends Admin {
    protected $layout = 'base';
    private $customer;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->customer = new Model_Customer();
    }

    /**
     * 用户列表
     * */
    public function indexAction()
    {
        $data = $this->_request->getQuery();
        $list = $this->customer->getList($data);
        $this->assign('data','customer');
        $this->assign('list',$list);
        $this->display();
    }


    /**
     * 新建客户
     * */
    public function addAction()
    {
        if ($this->_request->isPost()) {
            $data = $this->_request->getPost();
            $re = $this->customer->addInfo($data);
            if($re) fn_ajax_return(1,'添加成功',$re);
            fn_ajax_return(0,'添加失败');
        }else{
            $res = $this->customer->getInfo($this->_request->getQuery());
            $model_admin = new Model_Admin();
            $admin_info = $model_admin->getProcessAdmin();
            $this->assign('data','customer');
            $this->assign('res',$res);
            $this->assign('admin_info',$admin_info);
            $this->display();
        }
    }
    /**
     * 编辑客户
     * */
    public function editAction()
    {
        if ($this->_request->isPost()) {
            $data = $this->_request->getPost();
            $re = $this->customer->htEditInfo($data);
            if($re) fn_ajax_return(1,'操作成功','');
            fn_ajax_return(0,'操作成功');
        }
    }
    /**
     * 验证信息唯一性
     * */
    public function checkAction()
    {
        $data = $this->_request->getPost();
        if(!$data) fn_ajax_return(2,'验证字段不可为空');
        $re = $this->customer->dataOnly($data);
        if($re) fn_ajax_return(0,'已存在');
        fn_ajax_return(1,'可用');
    }

    /**
     * 冻结
     * */
    public function frozenAction()
    {
        $data = $this->_request->getPost();
        if(!isset($data['id']) || !$data['id'] || !isset($data['status']) || !$data['status']){
            fn_ajax_return(0,'非法操作','');
        }
        $res = $this->customer->frozen($data);
        if($res) fn_ajax_return(1,'操作成功','');
        fn_ajax_return(0,'操作失败','');
    }

}