<?php
/**
 * Created by IntelliJ IDEA.
 * User: lidc
 * Date: 17-8-14
 * Time: 下午5:51
 */
class Controller_System extends Admin{

    protected $layout = 'base';
    private $task;
    private $admin;
    private $position;
    private $operation;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->task = new Model_Task();
        $this->admin = new Model_Admin();
        $this->position = new Model_Position();
        $this->operation = new Model_Operation();
    }

    /**
     * 权限管理列表
     * */
    public function indexAction()
    {
        $data =$this->_request->getQuery();
        $info = $this->_session->get('admin_info');
        $position_id = isset($data['position_id'])?$data['position_id']:$info['position_id'];
        $positionList = $this->task->getList($position_id);
        $position = $this->position->getlist();
        $navAll = $this->task->getAllList();
        $selected = $this->operation->getTask($position_id);
        $this->assign('positionList',$positionList);
        $this->assign('position_id',$position_id);
        $this->assign('selected',$selected);
        $this->assign('position',$position);
        $this->assign('navAll',$navAll);
        $this->assign('data','system');
        $this->display();
    }

    /**
     * 权限修改
     * */
    public function editJurisdictionAction()
    {
        if ($this->_request->isPost()) {
            $re = $this->operation->editJurisdiction($this->_request->getPost());
            if ($re) fn_ajax_return(1, '修改成功', $re);
            fn_ajax_return(0, '修改失败');
        }
    }

    /**
     * 新权限组职位添加
     * */
    public function addOperAction()
    {
        $data = $this->_request->getPost();
        $re = $this->position->add($data);
        if($re) fn_ajax_return(1,'添加成功',$re);
        fn_ajax_return(0,'添加失败');
    }


    /**
     * 后台用户管理
     * */
    public function userAction()
    {
        $list = $this->admin->getList($this->_request->getQuery());
        $this->assign('data','system');
        $this->assign('list',$list);
        $this->display();
    }

    /**
     * 新建客户
     * */
    public function adduserAction()
    {
        if ($this->_request->isPost()) {
            $data = $this->_request->getPost();
            $re = $this->admin->addInfo($data);
            if($re) fn_ajax_return(1,'添加成功',$re);
            fn_ajax_return(0,'添加失败');
        }else{
            $res = $this->admin->getInfo($this->_request->getQuery());
            $model_position = new Model_Position();
            $positions = $model_position->select('*',[]);
            $this->assign('data','system');
            $this->assign('res',$res);
            $this->assign('positions',$positions);
            $this->display();
        }
    }
    /**
     * 编辑客户
     * */
    public function editAction()
    {
        if ($this->_request->isPost()) {
            $data = $this->_request->getPost();
            $re = $this->admin->editInfo($data);
            if($re) fn_ajax_return(1,'操作成功','');
            fn_ajax_return(0,'操作成功');
        }
    }

    /**
     * 冻结
     * */
    public function frozenAction()
    {
        $data = $this->_request->getPost();
        if(!isset($data['id']) || !$data['id'] || !isset($data['status']) || !$data['status']){
            fn_ajax_return(0,'非法操作','');
        }
        $res = $this->admin->frozen($data);
        if($res) fn_ajax_return(1,'操作成功','');
        fn_ajax_return(0,'操作失败','');
    }


}
